[package]
name = "zinoma"
version = "0.0.7"
authors = ["Florent Bécart <florent.becart@gmail.com>"]
edition = "2018"

categories = ["command-line-utilities", "concurrency", "development-tools", "development-tools::build-utils", "filesystem"]
documentation = "https://github.com/fbecart/zinoma/blob/master/README.md"
description = "Make your build flow incremental"
homepage = "https://github.com/fbecart/zinoma"
keywords = ["parallel", "incremental", "build", "tool", "watch"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/fbecart/zinoma"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
crossbeam = "=0.7.3"
duct = "0.13"
walkdir = "2"
notify = { version = "=5.0.0-pre.2", features = ["serde"] }
clap = "3.0.0-beta.1"
clap_generate = "3.0.0-beta.1"
log = "0.4.8"
stderrlog = "0.4.3"
fasthash = "0.4"
anyhow = "1.0.28"
serde_json = "1.0"
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
